const data = [
  {
    name: "U92",
    square: "126",
    area: "6.6",
    available: "true",
    price: "по запросу",
    images: [
      "../images/house1/house1.jpg",
      "../images/house1/house2.jpg",
      "../images/house1/house3.jpg",
      "../images/house1/house4.jpg",
      "../images/house1/house5.jpg",
      "../images/house1/house6.jpg",
    ],
    floors: ["../images/house1/first.jpg", "../images/house1/second.jpg"],
    id: 1,
  },
  {
    name: "U19",
    square: "172.9",
    area: "4.44",
    available: "true",
    price: "по запросу",
    images: [
      "../images/house2/house1.jpg",
      "../images/house2/house2.jpg",
      "../images/house2/house3.jpg",
      "../images/house2/house4.jpg",
      "../images/house2/house5.jpg",
    ],
    floors: ["../images/house2/first.jpg", "../images/house2/second.jpg"],
    id: 2,
  },
  {
    name: "UX4",
    square: "134.85",
    area: "10",
    available: "false",
    price: "2 500 000",
    images: [
      "../images/house3/house1.jpg",
      "../images/house3/house2.jpg",
      "../images/house3/house3.jpg",
      "../images/house3/house4.jpg",
      "../images/house3/house5.jpg",
    ],
    floors: ["../images/house3/first.jpg", "../images/house3/second.jpg"],
    id: 3,
  },
  {
    name: "U05",
    square: "132",
    area: "7.01",
    available: "none",
    price: "1 500 000",
    images: [
      "../images/house4/house1.jpg",
      "../images/house4/house2.jpg",
      "../images/house4/house3.jpg",
      "../images/house4/house4.jpg",
      "../images/house4/house5.jpg",
      "../images/house4/house6.jpg",
    ],
    floors: ["../images/house4/first.jpg", "../images/house4/second.jpg"],
    id: 4,
  },
  {
    name: "U93",
    square: "158",
    area: "4.55",
    available: "false",
    price: "2 199 000",
    images: [
      "../images/house5/house1.jpg",
      "../images/house5/house2.jpg",
      "../images/house5/house3.jpg",
      "../images/house5/house4.jpg",
      "../images/house5/house5.jpg",
      "../images/house5/house6.jpg",
    ],
    floors: ["../images/house5/first.jpg", "../images/house5/second.jpg"],
    id: 5,
  },
  {
    name: "X16",
    square: "160",
    area: "5.89",
    available: "true",
    price: "1 600 000",
    images: [
      "../images/house6/house1.jpg",
      "../images/house6/house2.jpg",
      "../images/house6/house3.jpg",
      "../images/house6/house4.jpg",
    ],
    floors: ["../images/house6/first.jpg", "../images/house6/second.jpg"],
    id: 6,
  },
  {
    name: "UX3",
    square: "137",
    area: "6.12",
    available: "none",
    price: "2 099 999",
    images: [
      "../images/house7/house1.jpg",
      "../images/house7/house2.jpg",
      "../images/house7/house3.jpg",
      "../images/house7/house4.jpg",
      "../images/house7/house5.jpg",
      "../images/house7/house6.jpg",
    ],
    floors: ["../images/house7/first.jpg", "../images/house7/second.jpg"],
    id: 7,
  },
  {
    name: "X82",
    square: "129.99",
    area: "6.45",
    available: "true",
    price: "2 000 000",
    images: [
      "../images/house8/house1.jpg",
      "../images/house8/house2.jpg",
      "../images/house8/house3.jpg",
      "../images/house8/house4.jpg",
      "../images/house8/house5.jpg",
    ],
    floors: ["../images/house8/first.jpg", "../images/house8/second.jpg"],
    id: 8,
  },
  {
    name: "T12",
    square: "264.5",
    area: "8.99",
    available: "none",
    price: "2 677 000",
    images: [
      "../images/house9/house1.jpg",
      "../images/house9/house2.jpg",
      "../images/house9/house3.jpg",
      "../images/house9/house4.jpg",
      "../images/house9/house5.jpg",
      "../images/house9/house6.jpg",
    ],
    floors: ["../images/house9/first.jpg", "../images/house9/second.jpg"],
    id: 9,
  },
  {
    name: "U11",
    square: "230.3",
    area: "7.45",
    available: "true",
    price: "по запросу",
    images: [
      "../images/house10/house1.jpg",
      "../images/house10/house2.jpg",
      "../images/house10/house3.jpg",
      "../images/house10/house4.jpg",
      "../images/house10/house5.jpg",
      "../images/house10/house6.jpg",
    ],
    floors: ["../images/house10/first.jpg", "../images/house10/second.jpg"],
    id: 10,
  },
  {
    name: "X62",
    square: "125",
    area: "6.6",
    available: "false",
    price: "по запросу",
    images: [
      "../images/house1/house1.jpg",
      "../images/house1/house2.jpg",
      "../images/house1/house3.jpg",
      "../images/house1/house4.jpg",
      "../images/house1/house5.jpg",
      "../images/house1/house6.jpg",
    ],
    floors: ["../images/house1/first.jpg", "../images/house1/second.jpg"],
    id: 11,
  },
  {
    name: "U1Z",
    square: "142.9",
    area: "5.54",
    available: "none",
    price: "по запросу",
    images: [
      "../images/house2/house1.jpg",
      "../images/house2/house2.jpg",
      "../images/house2/house3.jpg",
      "../images/house2/house4.jpg",
      "../images/house2/house5.jpg",
    ],
    floors: ["../images/house2/first.jpg", "../images/house2/second.jpg"],
    id: 12,
  },
  {
    name: "N5R",
    square: "239.85",
    area: "10",
    available: "true",
    price: "1 300 000",
    images: [
      "../images/house3/house1.jpg",
      "../images/house3/house2.jpg",
      "../images/house3/house3.jpg",
      "../images/house3/house4.jpg",
      "../images/house3/house5.jpg",
    ],
    floors: ["../images/house3/first.jpg", "../images/house3/second.jpg"],
    id: 13,
  },
  {
    name: "O4V",
    square: "225",
    area: "7.01",
    available: "false",
    price: "1 500 000",
    images: [
      "../images/house4/house1.jpg",
      "../images/house4/house2.jpg",
      "../images/house4/house3.jpg",
      "../images/house4/house4.jpg",
      "../images/house4/house5.jpg",
      "../images/house4/house6.jpg",
    ],
    floors: ["../images/house4/first.jpg", "../images/house4/second.jpg"],
    id: 14,
  },
  {
    name: "C4E",
    square: "148",
    area: "4.55",
    available: "true",
    price: "1 699 000",
    images: [
      "../images/house5/house1.jpg",
      "../images/house5/house2.jpg",
      "../images/house5/house3.jpg",
      "../images/house5/house4.jpg",
      "../images/house5/house5.jpg",
      "../images/house5/house6.jpg",
    ],
    floors: ["../images/house5/first.jpg", "../images/house5/second.jpg"],
    id: 15,
  },
  {
    name: "P0G",
    square: "172",
    area: "5.89",
    available: "none",
    price: "1 600 000",
    images: [
      "../images/house6/house1.jpg",
      "../images/house6/house2.jpg",
      "../images/house6/house3.jpg",
      "../images/house6/house4.jpg",
    ],
    floors: ["../images/house6/first.jpg", "../images/house6/second.jpg"],
    id: 16,
  },
  {
    name: "UI3",
    square: "187",
    area: "6.12",
    available: "false",
    price: "2 099 999",
    images: [
      "../images/house7/house1.jpg",
      "../images/house7/house2.jpg",
      "../images/house7/house3.jpg",
      "../images/house7/house4.jpg",
      "../images/house7/house5.jpg",
      "../images/house7/house6.jpg",
    ],
    floors: ["../images/house7/first.jpg", "../images/house7/second.jpg"],
    id: 17,
  },
  {
    name: "UX2",
    square: "177",
    area: "6.45",
    available: "true",
    price: "2 000 000",
    images: [
      "../images/house8/house1.jpg",
      "../images/house8/house2.jpg",
      "../images/house8/house3.jpg",
      "../images/house8/house4.jpg",
      "../images/house8/house5.jpg",
    ],
    floors: ["../images/house8/first.jpg", "../images/house8/second.jpg"],
    id: 18,
  },
  {
    name: "UB3",
    square: "264.5",
    area: "8.99",
    available: "none",
    price: "2 677 000",
    images: [
      "../images/house9/house1.jpg",
      "../images/house9/house2.jpg",
      "../images/house9/house3.jpg",
      "../images/house9/house4.jpg",
      "../images/house9/house5.jpg",
      "../images/house9/house6.jpg",
    ],
    floors: ["../images/house9/first.jpg", "../images/house9/second.jpg"],
    id: 19,
  },
  {
    name: "U2H",
    square: "230.3",
    area: "7.45",
    available: "true",
    price: "2 900 000",
    images: [
      "../images/house10/house1.jpg",
      "../images/house10/house2.jpg",
      "../images/house10/house3.jpg",
      "../images/house10/house4.jpg",
      "../images/house10/house5.jpg",
      "../images/house10/house6.jpg",
    ],
    floors: ["../images/house10/first.jpg", "../images/house10/second.jpg"],
    id: 20,
  },
  {
    name: "XJ4",
    square: "190",
    area: "5.89",
    available: "false",
    price: "1 600 000",
    images: [
      "../images/house6/house1.jpg",
      "../images/house6/house2.jpg",
      "../images/house6/house3.jpg",
      "../images/house6/house4.jpg",
    ],
    floors: ["../images/house6/first.jpg", "../images/house6/second.jpg"],
    id: 21,
  },
  {
    name: "UJ6",
    square: "155",
    area: "6.12",
    available: "false",
    price: "2 099 999",
    images: [
      "../images/house7/house1.jpg",
      "../images/house7/house2.jpg",
      "../images/house7/house3.jpg",
      "../images/house7/house4.jpg",
      "../images/house7/house5.jpg",
      "../images/house7/house6.jpg",
    ],
    floors: ["../images/house7/first.jpg", "../images/house7/second.jpg"],
    id: 22,
  },
  {
    name: "UX2",
    square: "166",
    area: "6.45",
    available: "false",
    price: "2 000 000",
    images: [
      "../images/house8/house1.jpg",
      "../images/house8/house2.jpg",
      "../images/house8/house3.jpg",
      "../images/house8/house4.jpg",
      "../images/house8/house5.jpg",
    ],
    floors: ["../images/house8/first.jpg", "../images/house8/second.jpg"],
    id: 23,
  },
  {
    name: "U8J",
    square: "264.5",
    area: "8.99",
    available: "true",
    price: "2 677 000",
    images: [
      "../images/house9/house1.jpg",
      "../images/house9/house2.jpg",
      "../images/house9/house3.jpg",
      "../images/house9/house4.jpg",
      "../images/house9/house5.jpg",
      "../images/house9/house6.jpg",
    ],
    floors: ["../images/house9/first.jpg", "../images/house9/second.jpg"],
    id: 24,
  },
  {
    name: "UP4",
    square: "230.3",
    area: "7.45",
    available: "none",
    price: "по запросу",
    images: [
      "../images/house10/house1.jpg",
      "../images/house10/house2.jpg",
      "../images/house10/house3.jpg",
      "../images/house10/house4.jpg",
      "../images/house10/house5.jpg",
      "../images/house10/house6.jpg",
    ],
    floors: ["../images/house10/first.jpg", "../images/house10/second.jpg"],
    id: 25,
  },
  {
    name: "XT4",
    square: "125",
    area: "6.6",
    available: "none",
    price: "по запросу",
    images: [
      "../images/house1/house1.jpg",
      "../images/house1/house2.jpg",
      "../images/house1/house3.jpg",
      "../images/house1/house4.jpg",
      "../images/house1/house5.jpg",
      "../images/house1/house6.jpg",
    ],
    floors: ["../images/house1/first.jpg", "../images/house1/second.jpg"],
    id: 26,
  },
  {
    name: "KL3",
    square: "182.9",
    area: "5.54",
    available: "false",
    price: "по запросу",
    images: [
      "../images/house2/house1.jpg",
      "../images/house2/house2.jpg",
      "../images/house2/house3.jpg",
      "../images/house2/house4.jpg",
      "../images/house2/house5.jpg",
    ],
    floors: ["../images/house2/first.jpg", "../images/house2/second.jpg"],
    id: 27,
  },
  {
    name: "MK3",
    square: "145",
    area: "10",
    available: "true",
    price: "1 300 000",
    images: [
      "../images/house3/house1.jpg",
      "../images/house3/house2.jpg",
      "../images/house3/house3.jpg",
      "../images/house3/house4.jpg",
      "../images/house3/house5.jpg",
    ],
    floors: ["../images/house3/first.jpg", "../images/house3/second.jpg"],
    id: 28,
  },
  {
    name: "JZ2",
    square: "175",
    area: "7.01",
    available: "true",
    price: "1 500 000",
    images: [
      "../images/house4/house1.jpg",
      "../images/house4/house2.jpg",
      "../images/house4/house3.jpg",
      "../images/house4/house4.jpg",
      "../images/house4/house5.jpg",
      "../images/house4/house6.jpg",
    ],
    floors: ["../images/house4/first.jpg", "../images/house4/second.jpg"],
    id: 29,
  },
  {
    name: "CC9",
    square: "198",
    area: "4.55",
    available: "false",
    price: "1 699 000",
    images: [
      "../images/house5/house1.jpg",
      "../images/house5/house2.jpg",
      "../images/house5/house3.jpg",
      "../images/house5/house4.jpg",
      "../images/house5/house5.jpg",
      "../images/house5/house6.jpg",
    ],
    floors: ["../images/house5/first.jpg", "../images/house5/second.jpg"],
    id: 30,
  },
  {
    name: "MZ5",
    square: "190",
    area: "5.89",
    available: "false",
    price: "1 600 000",
    images: [
      "../images/house6/house1.jpg",
      "../images/house6/house2.jpg",
      "../images/house6/house3.jpg",
      "../images/house6/house4.jpg",
    ],
    floors: ["../images/house6/first.jpg", "../images/house6/second.jpg"],
    id: 31,
  },
  {
    name: "U93",
    square: "181",
    area: "6.12",
    available: "true",
    price: "2 099 999",
    images: [
      "../images/house7/house1.jpg",
      "../images/house7/house2.jpg",
      "../images/house7/house3.jpg",
      "../images/house7/house4.jpg",
      "../images/house7/house5.jpg",
      "../images/house7/house6.jpg",
    ],
    floors: ["../images/house7/first.jpg", "../images/house7/second.jpg"],
    id: 32,
  },
  {
    name: "IJ2",
    square: "155",
    area: "6.45",
    available: "true",
    price: "2 000 000",
    images: [
      "../images/house8/house1.jpg",
      "../images/house8/house2.jpg",
      "../images/house8/house3.jpg",
      "../images/house8/house4.jpg",
      "../images/house8/house5.jpg",
    ],
    floors: ["../images/house8/first.jpg", "../images/house8/second.jpg"],
    id: 33,
  },
  {
    name: "UX12",
    square: "264.5",
    area: "8.99",
    available: "true",
    price: "2 677 000",
    images: [
      "../images/house9/house1.jpg",
      "../images/house9/house2.jpg",
      "../images/house9/house3.jpg",
      "../images/house9/house4.jpg",
      "../images/house9/house5.jpg",
      "../images/house9/house6.jpg",
    ],
    floors: ["../images/house9/first.jpg", "../images/house9/second.jpg"],
    id: 34,
  },
  {
    name: "UY2",
    square: "280.3",
    area: "7.45",
    available: "none",
    price: "2 900 000",
    images: [
      "../images/house10/house1.jpg",
      "../images/house10/house2.jpg",
      "../images/house10/house3.jpg",
      "../images/house10/house4.jpg",
      "../images/house10/house5.jpg",
      "../images/house10/house6.jpg",
    ],
    floors: ["../images/house10/first.jpg", "../images/house10/second.jpg"],
    id: 35,
  },
];

export default data;
